Bug/sc 456192/top value parameter should be present by default
CartoDB/raster-loader pull request #156
Opened 2024-12-04 15:16 UTC by rantolin

## Issue

https://app.shortcut.com/cartoteam/story/456192/top-value-parameter-should-be-present-by-default-in-raster-loader

## Proposed Changes

We have reversed the `--all_stats` flag into the `--omit_stats` in both `bigquery` and `snowflake` CLIs.

The new logic is that of calculate both top_values and quantiles by default and only omit them if specify by user `--omit_stats`.

In addition, we have fixed some other issues when:
1. Dealing with very sparse raster
2. Computing mean and stdev for exact stats
3. Colorinterp name

## Pull Request Checklist

- [X] I have tested the changes locally
- [X] I have added tests to cover my changes (if applicable)
- [ ] I have updated the documentation (if applicable)

2024-12-04 16:41 UTC, cayetanobv commented
@rantolin I think it's clearer `basic_stats` instead of `omit_stats` because it seems that no stat will be computed and that's not true.

2024-12-04 16:50 UTC, cayetanobv requested changes
Some comments added

2024-12-04 17:07 UTC, rantolin commented
> I think it's clearer `basic_stats` instead of `omit_stats` because it seems that no stat will be computed and that's not true.

I used `omit_stats` because it is something required in the ticket. But, yeah, happy to change it to `basic_stats` if everyone agrees

2024-12-04 17:13 UTC, cayetanobv commented
> > I think it's clearer `basic_stats` instead of `omit_stats` because it seems that no stat will be computed and that's not true.
> 
> I used `omit_stats` because it is something required in the ticket. But, yeah, happy to change it to `basic_stats` if everyone agrees

You are right it's in the ticket but it's confusing IMHO

2024-12-04 17:22 UTC, rantolin commented
> I don't see in the code avoiding the computation of quantiles and top values if the band has an integer data type.

Top values are used in categorical data so... we actually want to compute them for `integer` bands!

We could avoid to compute them for `float` bands. Anyway, a warning is printed out. Look line 602 in `io/common.py` file

2024-12-04 17:23 UTC, rantolin commented
> You are right it's in the ticket but it's confusing IMHO

Yes, agreed. It is not very accurate and I happy to change it. But shouldn't we agree with @anamanvil about this?

2024-12-05 00:58 UTC, cayetanobv commented
> > I don't see in the code avoiding the computation of quantiles and top values if the band has an integer data type.
> 
> Top values are used in categorical data so... we actually want to compute them for `integer` bands!
> 
> We could avoid to compute them for `float` bands. Anyway, a warning is printed out. Look line 602 in `io/common.py` file

My brain is broken today! :rofl: What I wanted to say is exactly the opposite: don't compute these stats for float bands. Okay, I see a warning in the code, but we don't want to compute top_values because it doesn't make sense for any practical purpose. The case of quantiles is different in that sense, but this stat is used to render the layer in Builder only if the data type is integer.

2024-12-05 09:55 UTC, rantolin commented
> My brain is broken today! 🤣 What I wanted to say is exactly the opposite: don't compute these stats for float bands. Okay, I see a warning in the code, but we don't want to compute top_values because it doesn't make sense for any practical purpose. The case of quantiles is different in that sense, but this stat is used to render the layer in Builder only if the data type is integer.

So was mine!
I changed the behaviour and we compute top values only for integer bands. I remove the warning as I don't see it necessary anymore.

2024-12-10 17:17 UTC, cayetanobv approved these changes

2024-12-11 06:15 UTC, volaya approved these changes

2024-12-11 06:16 UTC, merged